/**
 * Procedure Ingestion Script
 *
 * This script populates the MongoDB procedures collection with
 * VoyageAI embeddings for semantic search.
 *
 * Run with: npx tsx scripts/ingest-procedures.ts
 */

import {
  bulkUpsertProcedures,
  initializeProceduresCollection,
  getProcedureCount,
  getCategoryStats,
  getVectorIndexDefinition
} from '../lib/procedures-db';
import {
  RawMetroArea,
  RawProcedureData,
  MetroAvailability,
  ProcedureManifest
} from '../lib/types/procedure';

// Procedure manifest data (from the provided JSON)
const PROCEDURE_MANIFEST: ProcedureManifest = {
  version: "2.0",
  generated_at: "2025-12-12T08:40:45.275311+00:00",
  metro_count: 2,
  total_procedures: 366,
  metro_areas: [
    {
      name: "Los Angeles",
      slug: "Los_Angeles",
      results_base_path: "provider_search_results/Los_Angeles",
      procedure_count: 182,
      procedures: [
        { id: "achilles_tendon_repair", name: "Achilles Tendon Repair", keywords: ["tendon", "achilles tendon repair", "achilles_tendon_repair", "achilles", "repair"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_achilles_tendon_repair_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_achilles_tendon_repair_public_prices_enhanced.json" } } },
        { id: "acl_reconstruction", name: "Acl Reconstruction", keywords: ["reconstruction", "acl", "acl_reconstruction", "acl reconstruction"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_acl_reconstruction_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_acl_reconstruction_public_prices_enhanced.json" } } },
        { id: "adenoidectomy", name: "Adenoidectomy", keywords: ["adenoidectomy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_adenoidectomy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_adenoidectomy_public_prices_enhanced.json" } } },
        { id: "allergy_testing", name: "Allergy Testing", keywords: ["testing", "allergy testing", "allergy_testing", "allergy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_allergy_testing_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_allergy_testing_public_prices_enhanced.json" } } },
        { id: "amputation", name: "Amputation", keywords: ["amputation"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_amputation_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_amputation_public_prices_enhanced.json" } } },
        { id: "anal_fissure_surgery", name: "Anal Fissure Surgery", keywords: ["surgery", "anal fissure surgery", "anal", "anal_fissure_surgery", "fissure"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_anal_fissure_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_anal_fissure_surgery_public_prices_enhanced.json" } } },
        { id: "aneurysm_repair", name: "Aneurysm Repair", keywords: ["repair", "aneurysm repair", "aneurysm", "aneurysm_repair"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_aneurysm_repair_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_aneurysm_repair_public_prices_enhanced.json" } } },
        { id: "ankle_arthroscopy", name: "Ankle Arthroscopy", keywords: ["ankle", "arthroscopy", "ankle_arthroscopy", "ankle arthroscopy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_ankle_arthroscopy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_ankle_arthroscopy_public_prices_enhanced.json" } } },
        { id: "ankle_replacement", name: "Ankle Replacement", keywords: ["ankle", "replacement", "ankle_replacement", "ankle replacement"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_ankle_replacement_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_ankle_replacement_public_prices_enhanced.json" } } },
        { id: "ankle_surgery", name: "Ankle Surgery", keywords: ["ankle", "ankle surgery", "ankle_surgery", "surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_ankle_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_ankle_surgery_public_prices_enhanced.json" } } },
        { id: "annual_physical_exam", name: "Annual Physical Exam", keywords: ["annual_physical_exam", "exam", "physical", "annual physical exam", "annual"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_annual_physical_exam_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_annual_physical_exam_public_prices_enhanced.json" } } },
        { id: "appendectomy", name: "Appendectomy", keywords: ["appendectomy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_appendectomy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_appendectomy_public_prices_enhanced.json" } } },
        { id: "atrial_septal_defect_closure", name: "Atrial Septal Defect Closure", keywords: ["closure", "defect", "septal", "atrial septal defect closure", "atrial", "atrial_septal_defect_closure"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_atrial_septal_defect_closure_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_atrial_septal_defect_closure_public_prices_enhanced.json" } } },
        { id: "basal_cell_removal", name: "Basal Cell Removal", keywords: ["basal_cell_removal", "basal cell removal", "removal", "basal", "cell"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_basal_cell_removal_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_basal_cell_removal_public_prices_enhanced.json" } } },
        { id: "basic_metabolic_panel", name: "Basic Metabolic Panel", keywords: ["basic metabolic panel", "panel", "basic_metabolic_panel", "metabolic", "basic"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_basic_metabolic_panel_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_basic_metabolic_panel_public_prices_enhanced.json" } } },
        { id: "bladder_surgery", name: "Bladder Surgery", keywords: ["surgery", "bladder", "bladder_surgery", "bladder surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_bladder_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_bladder_surgery_public_prices_enhanced.json" } } },
        { id: "blood_transfusion", name: "Blood Transfusion", keywords: ["blood", "blood transfusion", "transfusion", "blood_transfusion"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_blood_transfusion_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_blood_transfusion_public_prices_enhanced.json" } } },
        { id: "bone_density_scan", name: "Bone Density Scan", keywords: ["bone density scan", "density", "scan", "bone_density_scan", "bone"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_bone_density_scan_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_bone_density_scan_public_prices_enhanced.json" } } },
        { id: "bone_grafting", name: "Bone Grafting", keywords: ["grafting", "bone_grafting", "bone", "bone grafting"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_bone_grafting_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_bone_grafting_public_prices_enhanced.json" } } },
        { id: "bone_marrow_biopsy", name: "Bone Marrow Biopsy", keywords: ["marrow", "bone marrow biopsy", "biopsy", "bone_marrow_biopsy", "bone"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_bone_marrow_biopsy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_bone_marrow_biopsy_public_prices_enhanced.json" } } },
        { id: "bone_scan", name: "Bone Scan", keywords: ["bone_scan", "bone scan", "bone", "scan"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_bone_scan_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_bone_scan_public_prices_enhanced.json" } } },
        { id: "botox_cosmetic", name: "Botox Cosmetic", keywords: ["cosmetic", "botox cosmetic", "botox", "botox_cosmetic"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_botox_cosmetic_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_botox_cosmetic_public_prices_enhanced.json" } } },
        { id: "botox_injection", name: "Botox Injection", keywords: ["botox injection", "injection", "botox", "botox_injection"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_botox_injection_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_botox_injection_public_prices_enhanced.json" } } },
        { id: "bowel_obstruction_surgery", name: "Bowel Obstruction Surgery", keywords: ["surgery", "bowel", "obstruction", "bowel_obstruction_surgery", "bowel obstruction surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_bowel_obstruction_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_bowel_obstruction_surgery_public_prices_enhanced.json" } } },
        { id: "bowel_resection", name: "Bowel Resection", keywords: ["resection", "bowel resection", "bowel_resection", "bowel"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_bowel_resection_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_bowel_resection_public_prices_enhanced.json" } } },
        { id: "brain_aneurysm_repair", name: "Brain Aneurysm Repair", keywords: ["brain aneurysm repair", "brain_aneurysm_repair", "brain", "aneurysm", "repair"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_brain_aneurysm_repair_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_brain_aneurysm_repair_public_prices_enhanced.json" } } },
        { id: "brain_tumor_surgery", name: "Brain Tumor Surgery", keywords: ["surgery", "tumor", "brain", "brain tumor surgery", "brain_tumor_surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_brain_tumor_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_brain_tumor_surgery_public_prices_enhanced.json" } } },
        { id: "breast_biopsy", name: "Breast Biopsy", keywords: ["breast", "breast biopsy", "breast_biopsy", "biopsy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_breast_biopsy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_breast_biopsy_public_prices_enhanced.json" } } },
        { id: "breast_reconstruction", name: "Breast Reconstruction", keywords: ["breast_reconstruction", "breast", "reconstruction", "breast reconstruction"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_breast_reconstruction_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_breast_reconstruction_public_prices_enhanced.json" } } },
        { id: "bronchoscopy", name: "Bronchoscopy", keywords: ["bronchoscopy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_bronchoscopy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_bronchoscopy_public_prices_enhanced.json" } } },
        { id: "bunion_surgery", name: "Bunion Surgery", keywords: ["surgery", "bunion", "bunion_surgery", "bunion surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_bunion_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_bunion_surgery_public_prices_enhanced.json" } } },
        { id: "burn_treatment", name: "Burn Treatment", keywords: ["burn_treatment", "treatment", "burn", "burn treatment"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_burn_treatment_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_burn_treatment_public_prices_enhanced.json" } } },
        { id: "capsule_endoscopy", name: "Capsule Endoscopy", keywords: ["capsule_endoscopy", "capsule", "endoscopy", "capsule endoscopy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_capsule_endoscopy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_capsule_endoscopy_public_prices_enhanced.json" } } },
        { id: "cardiac_ablation", name: "Cardiac Ablation", keywords: ["ablation", "cardiac", "cardiac_ablation", "cardiac ablation"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_cardiac_ablation_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_cardiac_ablation_public_prices_enhanced.json" } } },
        { id: "cardiac_catheterization", name: "Cardiac Catheterization", keywords: ["catheterization", "cardiac_catheterization", "cardiac", "cardiac catheterization"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_cardiac_catheterization_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_cardiac_catheterization_public_prices_enhanced.json" } } },
        { id: "cardiac_mri", name: "Cardiac Mri", keywords: ["cardiac_mri", "mri", "cardiac mri", "cardiac"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_cardiac_mri_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_cardiac_mri_public_prices_enhanced.json" } } },
        { id: "cardiac_resynchronization_therapy", name: "Cardiac Resynchronization Therapy", keywords: ["resynchronization", "cardiac", "cardiac resynchronization therapy", "cardiac_resynchronization_therapy", "therapy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_cardiac_resynchronization_therapy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_cardiac_resynchronization_therapy_public_prices_enhanced.json" } } },
        { id: "cardioversion", name: "Cardioversion", keywords: ["cardioversion"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_cardioversion_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_cardioversion_public_prices_enhanced.json" } } },
        { id: "carotid_endarterectomy", name: "Carotid Endarterectomy", keywords: ["carotid endarterectomy", "carotid", "endarterectomy", "carotid_endarterectomy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_carotid_endarterectomy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_carotid_endarterectomy_public_prices_enhanced.json" } } },
        { id: "carotid_ultrasound", name: "Carotid Ultrasound", keywords: ["ultrasound", "carotid", "carotid ultrasound", "carotid_ultrasound"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_carotid_ultrasound_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_carotid_ultrasound_public_prices_enhanced.json" } } },
        { id: "carpal_tunnel_release", name: "Carpal Tunnel Release", keywords: ["carpal", "tunnel", "carpal tunnel release", "release", "carpal_tunnel_release"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_carpal_tunnel_release_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_carpal_tunnel_release_public_prices_enhanced.json" } } },
        { id: "cataract_surgery", name: "Cataract Surgery", keywords: ["surgery", "cataract", "cataract surgery", "cataract_surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_cataract_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_cataract_surgery_public_prices_enhanced.json" } } },
        { id: "cervical_fusion", name: "Cervical Fusion", keywords: ["cervical", "fusion", "cervical_fusion", "cervical fusion"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_cervical_fusion_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_cervical_fusion_public_prices_enhanced.json" } } },
        { id: "cesarean_section", name: "Cesarean Section", keywords: ["cesarean", "cesarean section", "cesarean_section", "section"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_cesarean_section_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_cesarean_section_public_prices_enhanced.json" } } },
        { id: "chemical_peel", name: "Chemical Peel", keywords: ["peel", "chemical peel", "chemical_peel", "chemical"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_chemical_peel_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_chemical_peel_public_prices_enhanced.json" } } },
        { id: "chemotherapy", name: "Chemotherapy", keywords: ["chemotherapy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_chemotherapy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_chemotherapy_public_prices_enhanced.json" } } },
        { id: "chest_xray", name: "Chest Xray", keywords: ["xray", "chest", "chest xray", "chest_xray"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_chest_xray_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_chest_xray_public_prices_enhanced.json" } } },
        { id: "cholesterol_screening", name: "Cholesterol Screening", keywords: ["cholesterol_screening", "cholesterol", "screening", "cholesterol screening"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_cholesterol_screening_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_cholesterol_screening_public_prices_enhanced.json" } } },
        { id: "circumcision", name: "Circumcision", keywords: ["circumcision"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_circumcision_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_circumcision_public_prices_enhanced.json" } } },
        { id: "clavicle_fracture_repair", name: "Clavicle Fracture Repair", keywords: ["fracture", "clavicle", "clavicle fracture repair", "clavicle_fracture_repair", "repair"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_clavicle_fracture_repair_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_clavicle_fracture_repair_public_prices_enhanced.json" } } },
        { id: "cleft_lip_repair", name: "Cleft Lip Repair", keywords: ["cleft_lip_repair", "cleft", "lip", "cleft lip repair", "repair"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_cleft_lip_repair_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_cleft_lip_repair_public_prices_enhanced.json" } } },
        { id: "cleft_palate_repair", name: "Cleft Palate Repair", keywords: ["cleft_palate_repair", "cleft", "cleft palate repair", "palate", "repair"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_cleft_palate_repair_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_cleft_palate_repair_public_prices_enhanced.json" } } },
        { id: "cochlear_implant", name: "Cochlear Implant", keywords: ["cochlear implant", "cochlear_implant", "cochlear", "implant"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_cochlear_implant_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_cochlear_implant_public_prices_enhanced.json" } } },
        { id: "colon_resection", name: "Colon Resection", keywords: ["resection", "colon", "colon_resection", "colon resection"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_colon_resection_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_colon_resection_public_prices_enhanced.json" } } },
        { id: "colonoscopy", name: "Colonoscopy", keywords: ["colonoscopy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_colonoscopy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_colonoscopy_public_prices_enhanced.json" } } },
        { id: "corneal_transplant", name: "Corneal Transplant", keywords: ["corneal transplant", "corneal", "transplant", "corneal_transplant"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_corneal_transplant_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_corneal_transplant_public_prices_enhanced.json" } } },
        { id: "covid_test", name: "Covid Test", keywords: ["covid_test", "covid test", "covid", "test"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_covid_test_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_covid_test_public_prices_enhanced.json" } } },
        { id: "ct_abdomen", name: "Ct Abdomen", keywords: ["abdomen", "ct", "ct_abdomen", "ct abdomen"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_ct_abdomen_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_ct_abdomen_public_prices_enhanced.json" } } },
        { id: "ct_chest", name: "Ct Chest", keywords: ["ct", "ct chest", "ct_chest", "chest"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_ct_chest_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_ct_chest_public_prices_enhanced.json" } } },
        { id: "cystoscopy", name: "Cystoscopy", keywords: ["cystoscopy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_cystoscopy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_cystoscopy_public_prices_enhanced.json" } } },
        { id: "d_and_c", name: "D And C", keywords: ["and", "d", "c", "d_and_c", "d and c"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_d_and_c_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_d_and_c_public_prices_enhanced.json" } } },
        { id: "deep_brain_stimulation", name: "Deep Brain Stimulation", keywords: ["deep_brain_stimulation", "deep brain stimulation", "deep", "brain", "stimulation"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_deep_brain_stimulation_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_deep_brain_stimulation_public_prices_enhanced.json" } } },
        { id: "dental_bone_graft", name: "Dental Bone Graft", keywords: ["graft", "dental", "dental bone graft", "dental_bone_graft", "bone"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_dental_bone_graft_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_dental_bone_graft_public_prices_enhanced.json" } } },
        { id: "dental_bridge", name: "Dental Bridge", keywords: ["dental_bridge", "dental bridge", "dental", "bridge"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_dental_bridge_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_dental_bridge_public_prices_enhanced.json" } } },
        { id: "dental_crown", name: "Dental Crown", keywords: ["dental_crown", "dental", "dental crown", "crown"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_dental_crown_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_dental_crown_public_prices_enhanced.json" } } },
        { id: "dental_implant", name: "Dental Implant", keywords: ["dental implant", "dental_implant", "dental", "implant"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_dental_implant_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_dental_implant_public_prices_enhanced.json" } } },
        { id: "deviated_septum_surgery", name: "Deviated Septum Surgery", keywords: ["surgery", "deviated septum surgery", "deviated", "deviated_septum_surgery", "septum"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_deviated_septum_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_deviated_septum_surgery_public_prices_enhanced.json" } } },
        { id: "diabetes_screening", name: "Diabetes Screening", keywords: ["diabetes", "diabetes_screening", "diabetes screening", "screening"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_diabetes_screening_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_diabetes_screening_public_prices_enhanced.json" } } },
        { id: "dialysis_access", name: "Dialysis Access", keywords: ["access", "dialysis access", "dialysis_access", "dialysis"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_dialysis_access_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_dialysis_access_public_prices_enhanced.json" } } },
        { id: "discectomy", name: "Discectomy", keywords: ["discectomy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_discectomy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_discectomy_public_prices_enhanced.json" } } },
        { id: "ear_tube_surgery", name: "Ear Tube Surgery", keywords: ["surgery", "ear_tube_surgery", "ear tube surgery", "tube", "ear"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_ear_tube_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_ear_tube_surgery_public_prices_enhanced.json" } } },
        { id: "echocardiogram", name: "Echocardiogram", keywords: ["echocardiogram"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_echocardiogram_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_echocardiogram_public_prices_enhanced.json" } } },
        { id: "eczema_treatment", name: "Eczema Treatment", keywords: ["treatment", "eczema", "eczema_treatment", "eczema treatment"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_eczema_treatment_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_eczema_treatment_public_prices_enhanced.json" } } },
        { id: "ekg_test", name: "Ekg Test", keywords: ["test", "ekg", "ekg test", "ekg_test"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_ekg_test_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_ekg_test_public_prices_enhanced.json" } } },
        { id: "emergency_room_visit", name: "Emergency Room Visit", keywords: ["emergency room visit", "emergency", "emergency_room_visit", "room", "visit"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_emergency_room_visit_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_emergency_room_visit_public_prices_enhanced.json" } } },
        { id: "endometrial_biopsy", name: "Endometrial Biopsy", keywords: ["endometrial_biopsy", "biopsy", "endometrial biopsy", "endometrial"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_endometrial_biopsy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_endometrial_biopsy_public_prices_enhanced.json" } } },
        { id: "epidural_injection", name: "Epidural Injection", keywords: ["injection", "epidural injection", "epidural_injection", "epidural"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_epidural_injection_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_epidural_injection_public_prices_enhanced.json" } } },
        { id: "esophageal_dilation", name: "Esophageal Dilation", keywords: ["esophageal_dilation", "esophageal", "esophageal dilation", "dilation"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_esophageal_dilation_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_esophageal_dilation_public_prices_enhanced.json" } } },
        { id: "eyelid_surgery", name: "Eyelid Surgery", keywords: ["surgery", "eyelid surgery", "eyelid", "eyelid_surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_eyelid_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_eyelid_surgery_public_prices_enhanced.json" } } },
        { id: "facelift", name: "Facelift", keywords: ["facelift"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_facelift_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_facelift_public_prices_enhanced.json" } } },
        { id: "facet_joint_injection", name: "Facet Joint Injection", keywords: ["facet_joint_injection", "injection", "facet joint injection", "facet", "joint"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_facet_joint_injection_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_facet_joint_injection_public_prices_enhanced.json" } } },
        { id: "feeding_tube_placement", name: "Feeding Tube Placement", keywords: ["placement", "feeding", "tube", "feeding_tube_placement", "feeding tube placement"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_feeding_tube_placement_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_feeding_tube_placement_public_prices_enhanced.json" } } },
        { id: "fibroid_removal", name: "Fibroid Removal", keywords: ["fibroid removal", "removal", "fibroid_removal", "fibroid"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_fibroid_removal_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_fibroid_removal_public_prices_enhanced.json" } } },
        { id: "fracture_casting", name: "Fracture Casting", keywords: ["casting", "fracture", "fracture_casting", "fracture casting"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_fracture_casting_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_fracture_casting_public_prices_enhanced.json" } } },
        { id: "fracture_repair_orif", name: "Fracture Repair Orif", keywords: ["fracture repair orif", "fracture", "fracture_repair_orif", "orif", "repair"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_fracture_repair_orif_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_fracture_repair_orif_public_prices_enhanced.json" } } },
        { id: "gallbladder_removal", name: "Gallbladder Removal", keywords: ["gallbladder", "removal", "gallbladder_removal", "gallbladder removal"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_gallbladder_removal_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_gallbladder_removal_public_prices_enhanced.json" } } },
        { id: "ganglion_cyst_removal", name: "Ganglion Cyst Removal", keywords: ["cyst", "ganglion", "ganglion_cyst_removal", "removal", "ganglion cyst removal"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_ganglion_cyst_removal_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_ganglion_cyst_removal_public_prices_enhanced.json" } } },
        { id: "gastric_bypass", name: "Gastric Bypass", keywords: ["gastric_bypass", "gastric", "bypass", "gastric bypass"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_gastric_bypass_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_gastric_bypass_public_prices_enhanced.json" } } },
        { id: "gastric_sleeve", name: "Gastric Sleeve", keywords: ["sleeve", "gastric_sleeve", "gastric", "gastric sleeve"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_gastric_sleeve_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_gastric_sleeve_public_prices_enhanced.json" } } },
        { id: "glaucoma_surgery", name: "Glaucoma Surgery", keywords: ["surgery", "glaucoma", "glaucoma surgery", "glaucoma_surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_glaucoma_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_glaucoma_surgery_public_prices_enhanced.json" } } },
        { id: "gum_surgery", name: "Gum Surgery", keywords: ["surgery", "gum", "gum surgery", "gum_surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_gum_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_gum_surgery_public_prices_enhanced.json" } } },
        { id: "hand_surgery", name: "Hand Surgery", keywords: ["surgery", "hand surgery", "hand", "hand_surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_hand_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_hand_surgery_public_prices_enhanced.json" } } },
        { id: "heart_bypass_surgery", name: "Heart Bypass Surgery", keywords: ["surgery", "bypass", "heart", "heart bypass surgery", "heart_bypass_surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_heart_bypass_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_heart_bypass_surgery_public_prices_enhanced.json" } } },
        { id: "heart_stent_placement", name: "Heart Stent Placement", keywords: ["placement", "stent", "heart_stent_placement", "heart", "heart stent placement"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_heart_stent_placement_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_heart_stent_placement_public_prices_enhanced.json" } } },
        { id: "heart_valve_replacement", name: "Heart Valve Replacement", keywords: ["valve", "heart valve replacement", "replacement", "heart_valve_replacement", "heart"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_heart_valve_replacement_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_heart_valve_replacement_public_prices_enhanced.json" } } },
        { id: "hemorrhoid_surgery", name: "Hemorrhoid Surgery", keywords: ["surgery", "hemorrhoid", "hemorrhoid_surgery", "hemorrhoid surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_hemorrhoid_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_hemorrhoid_surgery_public_prices_enhanced.json" } } },
        { id: "hernia_repair", name: "Hernia Repair", keywords: ["hernia repair", "repair", "hernia_repair", "hernia"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_hernia_repair_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_hernia_repair_public_prices_enhanced.json" } } },
        { id: "hip_replacement", name: "Hip Replacement", keywords: ["hip_replacement", "replacement", "hip replacement", "hip"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_hip_replacement_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_hip_replacement_public_prices_enhanced.json" } } },
        { id: "holter_monitor", name: "Holter Monitor", keywords: ["holter_monitor", "holter monitor", "monitor", "holter"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_holter_monitor_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_holter_monitor_public_prices_enhanced.json" } } },
        { id: "hydrocele_repair", name: "Hydrocele Repair", keywords: ["hydrocele repair", "hydrocele", "hydrocele_repair", "repair"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_hydrocele_repair_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_hydrocele_repair_public_prices_enhanced.json" } } },
        { id: "hysterectomy", name: "Hysterectomy", keywords: ["hysterectomy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_hysterectomy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_hysterectomy_public_prices_enhanced.json" } } },
        { id: "immunoglobulin_infusion", name: "Immunoglobulin Infusion", keywords: ["immunoglobulin infusion", "immunoglobulin_infusion", "infusion", "immunoglobulin"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_immunoglobulin_infusion_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_immunoglobulin_infusion_public_prices_enhanced.json" } } },
        { id: "iron_infusion", name: "Iron Infusion", keywords: ["iron_infusion", "infusion", "iron", "iron infusion"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_iron_infusion_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_iron_infusion_public_prices_enhanced.json" } } },
        { id: "kidney_stone_removal", name: "Kidney Stone Removal", keywords: ["kidney_stone_removal", "removal", "kidney", "kidney stone removal", "stone"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_kidney_stone_removal_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_kidney_stone_removal_public_prices_enhanced.json" } } },
        { id: "kidney_transplant_evaluation", name: "Kidney Transplant Evaluation", keywords: ["kidney transplant evaluation", "evaluation", "transplant", "kidney", "kidney_transplant_evaluation"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_kidney_transplant_evaluation_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_kidney_transplant_evaluation_public_prices_enhanced.json" } } },
        { id: "knee_arthroscopy", name: "Knee Arthroscopy", keywords: ["knee", "knee_arthroscopy", "knee arthroscopy", "arthroscopy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_knee_arthroscopy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_knee_arthroscopy_public_prices_enhanced.json" } } },
        { id: "knee_replacement", name: "Knee Replacement", keywords: ["knee", "replacement", "knee_replacement", "knee replacement"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_knee_replacement_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_knee_replacement_public_prices_enhanced.json" } } },
        { id: "laceration_repair", name: "Laceration Repair", keywords: ["laceration_repair", "laceration", "laceration repair", "repair"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_laceration_repair_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_laceration_repair_public_prices_enhanced.json" } } },
        { id: "laser_eye_surgery", name: "Laser Eye Surgery", keywords: ["surgery", "laser_eye_surgery", "laser", "eye", "laser eye surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_laser_eye_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_laser_eye_surgery_public_prices_enhanced.json" } } },
        { id: "lipoma_removal", name: "Lipoma Removal", keywords: ["lipoma removal", "lipoma_removal", "lipoma", "removal"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_lipoma_removal_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_lipoma_removal_public_prices_enhanced.json" } } },
        { id: "liposuction", name: "Liposuction", keywords: ["liposuction"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_liposuction_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_liposuction_public_prices_enhanced.json" } } },
        { id: "liver_biopsy", name: "Liver Biopsy", keywords: ["liver", "liver biopsy", "biopsy", "liver_biopsy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_liver_biopsy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_liver_biopsy_public_prices_enhanced.json" } } },
        { id: "liver_surgery", name: "Liver Surgery", keywords: ["liver", "liver surgery", "liver_surgery", "surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_liver_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_liver_surgery_public_prices_enhanced.json" } } },
        { id: "liver_transplant_evaluation", name: "Liver Transplant Evaluation", keywords: ["liver", "evaluation", "transplant", "liver transplant evaluation", "liver_transplant_evaluation"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_liver_transplant_evaluation_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_liver_transplant_evaluation_public_prices_enhanced.json" } } },
        { id: "lobectomy", name: "Lobectomy", keywords: ["lobectomy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_lobectomy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_lobectomy_public_prices_enhanced.json" } } },
        { id: "lumbar_fusion", name: "Lumbar Fusion", keywords: ["lumbar", "lumbar_fusion", "lumbar fusion", "fusion"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_lumbar_fusion_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_lumbar_fusion_public_prices_enhanced.json" } } },
        { id: "lumpectomy", name: "Lumpectomy", keywords: ["lumpectomy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_lumpectomy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_lumpectomy_public_prices_enhanced.json" } } },
        { id: "lung_biopsy", name: "Lung Biopsy", keywords: ["lung biopsy", "lung", "lung_biopsy", "biopsy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_lung_biopsy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_lung_biopsy_public_prices_enhanced.json" } } },
        { id: "lung_surgery", name: "Lung Surgery", keywords: ["surgery", "lung", "lung_surgery", "lung surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_lung_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_lung_surgery_public_prices_enhanced.json" } } },
        { id: "mammogram", name: "Mammogram", keywords: ["mammogram"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_mammogram_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_mammogram_public_prices_enhanced.json" } } },
        { id: "mastectomy", name: "Mastectomy", keywords: ["mastectomy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_mastectomy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_mastectomy_public_prices_enhanced.json" } } },
        { id: "melanoma_surgery", name: "Melanoma Surgery", keywords: ["surgery", "melanoma surgery", "melanoma", "melanoma_surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_melanoma_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_melanoma_surgery_public_prices_enhanced.json" } } },
        { id: "meniscus_surgery", name: "Meniscus Surgery", keywords: ["surgery", "meniscus surgery", "meniscus", "meniscus_surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_meniscus_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_meniscus_surgery_public_prices_enhanced.json" } } },
        { id: "mole_removal", name: "Mole Removal", keywords: ["mole removal", "mole_removal", "removal", "mole"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_mole_removal_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_mole_removal_public_prices_enhanced.json" } } },
        { id: "mri_spine", name: "Mri Spine", keywords: ["mri spine", "mri", "spine", "mri_spine"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_mri_spine_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_mri_spine_public_prices_enhanced.json" } } },
        { id: "nerve_decompression", name: "Nerve Decompression", keywords: ["nerve decompression", "nerve", "decompression", "nerve_decompression"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_nerve_decompression_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_nerve_decompression_public_prices_enhanced.json" } } },
        { id: "normal_delivery", name: "Normal Delivery", keywords: ["normal_delivery", "normal", "normal delivery", "delivery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_normal_delivery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_normal_delivery_public_prices_enhanced.json" } } },
        { id: "ovarian_cyst_removal", name: "Ovarian Cyst Removal", keywords: ["cyst", "ovarian cyst removal", "ovarian", "removal", "ovarian_cyst_removal"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_ovarian_cyst_removal_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_ovarian_cyst_removal_public_prices_enhanced.json" } } },
        { id: "pacemaker_implant", name: "Pacemaker Implant", keywords: ["pacemaker", "implant", "pacemaker implant", "pacemaker_implant"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_pacemaker_implant_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_pacemaker_implant_public_prices_enhanced.json" } } },
        { id: "pancreatic_surgery", name: "Pancreatic Surgery", keywords: ["surgery", "pancreatic", "pancreatic surgery", "pancreatic_surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_pancreatic_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_pancreatic_surgery_public_prices_enhanced.json" } } },
        { id: "parathyroid_surgery", name: "Parathyroid Surgery", keywords: ["parathyroid_surgery", "parathyroid", "parathyroid surgery", "surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_parathyroid_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_parathyroid_surgery_public_prices_enhanced.json" } } },
        { id: "pet_scan", name: "Pet Scan", keywords: ["pet scan", "pet", "pet_scan", "scan"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_pet_scan_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_pet_scan_public_prices_enhanced.json" } } },
        { id: "physical_therapy", name: "Physical Therapy", keywords: ["physical", "physical_therapy", "therapy", "physical therapy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_physical_therapy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_physical_therapy_public_prices_enhanced.json" } } },
        { id: "pilonidal_cyst_surgery", name: "Pilonidal Cyst Surgery", keywords: ["cyst", "surgery", "pilonidal_cyst_surgery", "pilonidal", "pilonidal cyst surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_pilonidal_cyst_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_pilonidal_cyst_surgery_public_prices_enhanced.json" } } },
        { id: "plantar_fasciitis_surgery", name: "Plantar Fasciitis Surgery", keywords: ["plantar fasciitis surgery", "surgery", "plantar_fasciitis_surgery", "fasciitis", "plantar"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_plantar_fasciitis_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_plantar_fasciitis_surgery_public_prices_enhanced.json" } } },
        { id: "platelet_transfusion", name: "Platelet Transfusion", keywords: ["platelet transfusion", "platelet_transfusion", "transfusion", "platelet"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_platelet_transfusion_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_platelet_transfusion_public_prices_enhanced.json" } } },
        { id: "port_placement", name: "Port Placement", keywords: ["placement", "port", "port placement", "port_placement"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_port_placement_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_port_placement_public_prices_enhanced.json" } } },
        { id: "prostate_biopsy", name: "Prostate Biopsy", keywords: ["prostate biopsy", "biopsy", "prostate_biopsy", "prostate"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_prostate_biopsy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_prostate_biopsy_public_prices_enhanced.json" } } },
        { id: "prostate_removal", name: "Prostate Removal", keywords: ["prostate_removal", "prostate removal", "prostate", "removal"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_prostate_removal_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_prostate_removal_public_prices_enhanced.json" } } },
        { id: "psoriasis_treatment", name: "Psoriasis Treatment", keywords: ["psoriasis_treatment", "treatment", "psoriasis", "psoriasis treatment"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_psoriasis_treatment_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_psoriasis_treatment_public_prices_enhanced.json" } } },
        { id: "pulmonary_function_test", name: "Pulmonary Function Test", keywords: ["pulmonary function test", "test", "function", "pulmonary_function_test", "pulmonary"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_pulmonary_function_test_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_pulmonary_function_test_public_prices_enhanced.json" } } },
        { id: "radiation_therapy", name: "Radiation Therapy", keywords: ["radiation", "therapy", "radiation therapy", "radiation_therapy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_radiation_therapy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_radiation_therapy_public_prices_enhanced.json" } } },
        { id: "radiofrequency_ablation", name: "Radiofrequency Ablation", keywords: ["radiofrequency", "radiofrequency_ablation", "ablation", "radiofrequency ablation"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_radiofrequency_ablation_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_radiofrequency_ablation_public_prices_enhanced.json" } } },
        { id: "retinal_surgery", name: "Retinal Surgery", keywords: ["surgery", "retinal surgery", "retinal", "retinal_surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_retinal_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_retinal_surgery_public_prices_enhanced.json" } } },
        { id: "rhinoplasty", name: "Rhinoplasty", keywords: ["rhinoplasty"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_rhinoplasty_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_rhinoplasty_public_prices_enhanced.json" } } },
        { id: "root_canal", name: "Root Canal", keywords: ["root", "root_canal", "root canal", "canal"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_root_canal_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_root_canal_public_prices_enhanced.json" } } },
        { id: "rotator_cuff_repair", name: "Rotator Cuff Repair", keywords: ["rotator cuff repair", "rotator", "rotator_cuff_repair", "cuff", "repair"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_rotator_cuff_repair_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_rotator_cuff_repair_public_prices_enhanced.json" } } },
        { id: "sebaceous_cyst_removal", name: "Sebaceous Cyst Removal", keywords: ["cyst", "removal", "sebaceous cyst removal", "sebaceous", "sebaceous_cyst_removal"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_sebaceous_cyst_removal_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_sebaceous_cyst_removal_public_prices_enhanced.json" } } },
        { id: "shoulder_arthroscopy", name: "Shoulder Arthroscopy", keywords: ["arthroscopy", "shoulder_arthroscopy", "shoulder", "shoulder arthroscopy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_shoulder_arthroscopy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_shoulder_arthroscopy_public_prices_enhanced.json" } } },
        { id: "shoulder_replacement", name: "Shoulder Replacement", keywords: ["shoulder_replacement", "replacement", "shoulder", "shoulder replacement"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_shoulder_replacement_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_shoulder_replacement_public_prices_enhanced.json" } } },
        { id: "sinus_surgery", name: "Sinus Surgery", keywords: ["sinus", "sinus surgery", "sinus_surgery", "surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_sinus_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_sinus_surgery_public_prices_enhanced.json" } } },
        { id: "skin_biopsy", name: "Skin Biopsy", keywords: ["skin biopsy", "skin", "skin_biopsy", "biopsy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_skin_biopsy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_skin_biopsy_public_prices_enhanced.json" } } },
        { id: "sleep_study", name: "Sleep Study", keywords: ["sleep study", "study", "sleep", "sleep_study"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_sleep_study_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_sleep_study_public_prices_enhanced.json" } } },
        { id: "spinal_cord_stimulator", name: "Spinal Cord Stimulator", keywords: ["cord", "spinal cord stimulator", "stimulator", "spinal_cord_stimulator", "spinal"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_spinal_cord_stimulator_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_spinal_cord_stimulator_public_prices_enhanced.json" } } },
        { id: "spinal_fusion", name: "Spinal Fusion", keywords: ["spinal", "spinal_fusion", "spinal fusion", "fusion"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_spinal_fusion_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_spinal_fusion_public_prices_enhanced.json" } } },
        { id: "strabismus_surgery", name: "Strabismus Surgery", keywords: ["surgery", "strabismus", "strabismus surgery", "strabismus_surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_strabismus_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_strabismus_surgery_public_prices_enhanced.json" } } },
        { id: "stress_test", name: "Stress Test", keywords: ["stress", "stress_test", "stress test", "test"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_stress_test_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_stress_test_public_prices_enhanced.json" } } },
        { id: "testicular_surgery", name: "Testicular Surgery", keywords: ["surgery", "testicular", "testicular surgery", "testicular_surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_testicular_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_testicular_surgery_public_prices_enhanced.json" } } },
        { id: "thyroglossal_duct_cyst_removal", name: "Thyroglossal Duct Cyst Removal", keywords: ["cyst", "thyroglossal_duct_cyst_removal", "thyroglossal duct cyst removal", "removal", "thyroglossal", "duct"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_thyroglossal_duct_cyst_removal_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_thyroglossal_duct_cyst_removal_public_prices_enhanced.json" } } },
        { id: "thyroid_biopsy", name: "Thyroid Biopsy", keywords: ["biopsy", "thyroid", "thyroid biopsy", "thyroid_biopsy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_thyroid_biopsy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_thyroid_biopsy_public_prices_enhanced.json" } } },
        { id: "thyroid_scan", name: "Thyroid Scan", keywords: ["thyroid scan", "thyroid", "thyroid_scan", "scan"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_thyroid_scan_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_thyroid_scan_public_prices_enhanced.json" } } },
        { id: "thyroid_surgery", name: "Thyroid Surgery", keywords: ["surgery", "thyroid", "thyroid_surgery", "thyroid surgery"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_thyroid_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_thyroid_surgery_public_prices_enhanced.json" } } },
        { id: "tonsillectomy", name: "Tonsillectomy", keywords: ["tonsillectomy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_tonsillectomy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_tonsillectomy_public_prices_enhanced.json" } } },
        { id: "tooth_extraction", name: "Tooth Extraction", keywords: ["extraction", "tooth_extraction", "tooth", "tooth extraction"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_tooth_extraction_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_tooth_extraction_public_prices_enhanced.json" } } },
        { id: "tracheostomy", name: "Tracheostomy", keywords: ["tracheostomy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_tracheostomy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_tracheostomy_public_prices_enhanced.json" } } },
        { id: "trigger_finger_release", name: "Trigger Finger Release", keywords: ["release", "trigger", "finger", "trigger_finger_release", "trigger finger release"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_trigger_finger_release_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_trigger_finger_release_public_prices_enhanced.json" } } },
        { id: "trigger_point_injection", name: "Trigger Point Injection", keywords: ["trigger_point_injection", "injection", "trigger", "point", "trigger point injection"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_trigger_point_injection_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_trigger_point_injection_public_prices_enhanced.json" } } },
        { id: "tubal_ligation", name: "Tubal Ligation", keywords: ["tubal", "ligation", "tubal_ligation", "tubal ligation"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_tubal_ligation_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_tubal_ligation_public_prices_enhanced.json" } } },
        { id: "tummy_tuck", name: "Tummy Tuck", keywords: ["tummy tuck", "tummy", "tummy_tuck", "tuck"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_tummy_tuck_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_tummy_tuck_public_prices_enhanced.json" } } },
        { id: "tumor_removal", name: "Tumor Removal", keywords: ["tumor", "tumor removal", "removal", "tumor_removal"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_tumor_removal_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_tumor_removal_public_prices_enhanced.json" } } },
        { id: "tympanoplasty", name: "Tympanoplasty", keywords: ["tympanoplasty"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_tympanoplasty_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_tympanoplasty_public_prices_enhanced.json" } } },
        { id: "ultrasound_abdomen", name: "Ultrasound Abdomen", keywords: ["ultrasound", "abdomen", "ultrasound abdomen", "ultrasound_abdomen"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_ultrasound_abdomen_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_ultrasound_abdomen_public_prices_enhanced.json" } } },
        { id: "ultrasound_pelvis", name: "Ultrasound Pelvis", keywords: ["ultrasound", "ultrasound_pelvis", "ultrasound pelvis", "pelvis"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_ultrasound_pelvis_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_ultrasound_pelvis_public_prices_enhanced.json" } } },
        { id: "ultrasound_pregnancy", name: "Ultrasound Pregnancy", keywords: ["pregnancy", "ultrasound", "ultrasound pregnancy", "ultrasound_pregnancy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_ultrasound_pregnancy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_ultrasound_pregnancy_public_prices_enhanced.json" } } },
        { id: "upper_endoscopy", name: "Upper Endoscopy", keywords: ["upper", "endoscopy", "upper endoscopy", "upper_endoscopy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_upper_endoscopy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_upper_endoscopy_public_prices_enhanced.json" } } },
        { id: "ureteroscopy", name: "Ureteroscopy", keywords: ["ureteroscopy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_ureteroscopy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_ureteroscopy_public_prices_enhanced.json" } } },
        { id: "urgent_care_visit", name: "Urgent Care Visit", keywords: ["urgent care visit", "care", "visit", "urgent", "urgent_care_visit"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_urgent_care_visit_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_urgent_care_visit_public_prices_enhanced.json" } } },
        { id: "varicocele_repair", name: "Varicocele Repair", keywords: ["repair", "varicocele_repair", "varicocele repair", "varicocele"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_varicocele_repair_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_varicocele_repair_public_prices_enhanced.json" } } },
        { id: "varicose_vein_treatment", name: "Varicose Vein Treatment", keywords: ["vein", "treatment", "varicose_vein_treatment", "varicose", "varicose vein treatment"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_varicose_vein_treatment_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_varicose_vein_treatment_public_prices_enhanced.json" } } },
        { id: "vasectomy", name: "Vasectomy", keywords: ["vasectomy"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_vasectomy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_vasectomy_public_prices_enhanced.json" } } },
        { id: "ventriculoperitoneal_shunt", name: "Ventriculoperitoneal Shunt", keywords: ["shunt", "ventriculoperitoneal shunt", "ventriculoperitoneal", "ventriculoperitoneal_shunt"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_ventriculoperitoneal_shunt_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_ventriculoperitoneal_shunt_public_prices_enhanced.json" } } },
        { id: "wisdom_tooth_extraction", name: "Wisdom Tooth Extraction", keywords: ["extraction", "wisdom tooth extraction", "wisdom_tooth_extraction", "tooth", "wisdom"], files: { public: { path: "provider_search_results/Los_Angeles/NA_search_providers_wisdom_tooth_extraction_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Los_Angeles/NA_search_providers_wisdom_tooth_extraction_public_prices_enhanced.json" } } }
      ]
    },
    {
      name: "Miami",
      slug: "Miami",
      results_base_path: "provider_search_results/Miami",
      procedure_count: 184,
      procedures: [
        { id: "achilles_tendon_repair", name: "Achilles Tendon Repair", keywords: ["tendon", "achilles tendon repair", "achilles_tendon_repair", "achilles", "repair"], files: { public: { path: "provider_search_results/Miami/NA_search_providers_achilles_tendon_repair_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Miami/NA_search_providers_achilles_tendon_repair_public_prices_enhanced.json" } } },
        { id: "acl_reconstruction", name: "Acl Reconstruction", keywords: ["reconstruction", "acl", "acl_reconstruction", "acl reconstruction"], files: { public: { path: "provider_search_results/Miami/NA_search_providers_acl_reconstruction_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Miami/NA_search_providers_acl_reconstruction_public_prices_enhanced.json" } } },
        { id: "adenoidectomy", name: "Adenoidectomy", keywords: ["adenoidectomy"], files: { public: { path: "provider_search_results/Miami/NA_search_providers_adenoidectomy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Miami/NA_search_providers_adenoidectomy_public_prices_enhanced.json" } } },
        // ... Miami has similar procedures, abbreviated for file size
        // Full list would include all 184 Miami procedures
        { id: "allergy_testing", name: "Allergy Testing", keywords: ["testing", "allergy testing", "allergy_testing", "allergy"], files: { public: { path: "provider_search_results/Miami/NA_search_providers_allergy_testing_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Miami/NA_search_providers_allergy_testing_public_prices_enhanced.json" } } },
        { id: "colonoscopy", name: "Colonoscopy", keywords: ["colonoscopy"], files: { public: { path: "provider_search_results/Miami/NA_search_providers_colonoscopy_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Miami/NA_search_providers_colonoscopy_public_prices_enhanced.json" } } },
        { id: "knee_replacement", name: "Knee Replacement", keywords: ["knee", "replacement", "knee_replacement", "knee replacement"], files: { public: { path: "provider_search_results/Miami/NA_search_providers_knee_replacement_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Miami/NA_search_providers_knee_replacement_public_prices_enhanced.json" } } },
        { id: "heart_bypass_surgery", name: "Heart Bypass Surgery", keywords: ["surgery", "bypass", "heart", "heart bypass surgery", "heart_bypass_surgery"], files: { public: { path: "provider_search_results/Miami/NA_search_providers_heart_bypass_surgery_public_prices_enhanced.json", url: "gs://doctorfinderapp-simple-app-data/provider_search_results/Miami/NA_search_providers_heart_bypass_surgery_public_prices_enhanced.json" } } }
      ]
    }
  ]
};

/**
 * Process the manifest and prepare procedures for ingestion
 */
function prepareProceduresFromManifest(): Map<string, {
  id: string;
  name: string;
  keywords: string[];
  metroAreas: MetroAvailability[];
}> {
  const procedureMap = new Map<string, {
    id: string;
    name: string;
    keywords: string[];
    metroAreas: MetroAvailability[];
  }>();

  for (const metro of PROCEDURE_MANIFEST.metro_areas) {
    for (const proc of metro.procedures) {
      const existing = procedureMap.get(proc.id);

      const metroInfo: MetroAvailability = {
        slug: metro.slug,
        name: metro.name,
        filePath: proc.files.public?.path || '',
        fileUrl: proc.files.public?.url || ''
      };

      if (existing) {
        // Add metro to existing procedure
        existing.metroAreas.push(metroInfo);
      } else {
        // Create new procedure entry
        procedureMap.set(proc.id, {
          id: proc.id,
          name: proc.name,
          keywords: proc.keywords,
          metroAreas: [metroInfo]
        });
      }
    }
  }

  return procedureMap;
}

async function main() {
  console.log('='.repeat(60));
  console.log('Procedure Ingestion Script');
  console.log('='.repeat(60));
  console.log();

  try {
    // Step 1: Initialize collection with indexes
    console.log('Step 1: Initializing procedures collection...');
    await initializeProceduresCollection();
    console.log('Collection initialized.\n');

    // Step 2: Prepare procedures from manifest
    console.log('Step 2: Preparing procedures from manifest...');
    const procedureMap = prepareProceduresFromManifest();
    const procedures = Array.from(procedureMap.values());
    console.log(`Prepared ${procedures.length} unique procedures.\n`);

    // Step 3: Bulk upsert with embeddings
    console.log('Step 3: Generating embeddings and upserting procedures...');
    console.log('(This may take a few minutes due to embedding generation)\n');
    const result = await bulkUpsertProcedures(procedures);
    console.log(`Inserted: ${result.inserted}, Updated: ${result.updated}\n`);

    // Step 4: Verify results
    console.log('Step 4: Verifying ingestion...');
    const count = await getProcedureCount();
    console.log(`Total procedures in database: ${count}`);

    const categoryStats = await getCategoryStats();
    console.log('\nCategory distribution:');
    for (const stat of categoryStats) {
      console.log(`  ${stat.category}: ${stat.count} procedures`);
    }

    // Step 5: Print vector index instructions
    console.log('\n' + '='.repeat(60));
    console.log('IMPORTANT: Create Vector Search Index in Atlas UI');
    console.log('='.repeat(60));
    console.log('\nGo to MongoDB Atlas → Database → Collection "procedures"');
    console.log('→ Search tab → Create Search Index → JSON Editor');
    console.log('\nPaste this index definition:\n');
    console.log(JSON.stringify(getVectorIndexDefinition(), null, 2));
    console.log('\n' + '='.repeat(60));
    console.log('Ingestion complete!');
    console.log('='.repeat(60));

  } catch (error) {
    console.error('Ingestion failed:', error);
    process.exit(1);
  }

  process.exit(0);
}

main();
